language: python

python:
- 2.7

before_script:
- pip install -r requirements.txt
- pip install -r requirements-test.txt

script:
- make test
- make bandit

after_success:
- coveralls
- coverage xml
- python-codacy-coverage -r coverage.xml

deploy:
  - provider: pypi
    distributions: sdist
    server: https://test.pypi.org/legacy/
    user: iamjohnnym
    password:
      secure: K2swV6OVouJWL8grGGSmrZ/iq6cWuE3cIcXSTnKMSqSyD41EF8SNk+fTSY1dv17d0fxClWZ5ub5u9XHeJy9wuKsl9gyaPPFvlnF2HVVoKdnfr+J6mot8AIh3zpdA+21AzlX3NssT5Y+5RLypOPLzyDHJm7fEidqRSnIDacnN6vRo6o/PbFgGDTw3sK6E7z8Ppg9BjGtsBOsK3NH5pfFkDVdEzO+GzPRoegDTpackDvg7w8d/7bAbKcdQhDVzNeU2fSS/eBd1vwG5LVpB9pEqOAIfGihIPgI81RMj4gJtKiEAO/9zbvna6xgGo6rf+U8N2ApeTDQfvplG2VMS4xdINdtyEEDyxYBkey+r2dM7+uHnZmOt61UXf4pZQVOj0aGjF7SaQgTKfDu8tgsw02fsA2RfqFLvF+X5CYL33nPGLaWbQHUgSP0vpe26NWGwA4G/39XQP56QckkTx9RwqZ+f/FreBGNNnvQ/qQ0yPaZYMmo6JJ6RUibUVXHqeN2NfCrjHA275SR6e1Dz8ZbZD5KNwzR6D/FJpgMl40ZiZC3uUipDulInNwoAy+W69ZUVSQUrpcY1tIckrkrOWQaqdKR+HzRl4mxbpXZDUWcd2a72xHKe28/wjd+FH63HIkLb2N1M2vlGmdh1fch8paPjPo8BunB1QTJ+zxoS8xB5jWPZqmQ=
    on:
      branch: staging
      tags: false
      condition: $TRAVIS_PYTHON_VERSION = "2.7"
  - provider: pypi
    distributions: sdist
    server: https://test.pypi.org/legacy/
    user: iamjohnnym
    password:
      secure: K2swV6OVouJWL8grGGSmrZ/iq6cWuE3cIcXSTnKMSqSyD41EF8SNk+fTSY1dv17d0fxClWZ5ub5u9XHeJy9wuKsl9gyaPPFvlnF2HVVoKdnfr+J6mot8AIh3zpdA+21AzlX3NssT5Y+5RLypOPLzyDHJm7fEidqRSnIDacnN6vRo6o/PbFgGDTw3sK6E7z8Ppg9BjGtsBOsK3NH5pfFkDVdEzO+GzPRoegDTpackDvg7w8d/7bAbKcdQhDVzNeU2fSS/eBd1vwG5LVpB9pEqOAIfGihIPgI81RMj4gJtKiEAO/9zbvna6xgGo6rf+U8N2ApeTDQfvplG2VMS4xdINdtyEEDyxYBkey+r2dM7+uHnZmOt61UXf4pZQVOj0aGjF7SaQgTKfDu8tgsw02fsA2RfqFLvF+X5CYL33nPGLaWbQHUgSP0vpe26NWGwA4G/39XQP56QckkTx9RwqZ+f/FreBGNNnvQ/qQ0yPaZYMmo6JJ6RUibUVXHqeN2NfCrjHA275SR6e1Dz8ZbZD5KNwzR6D/FJpgMl40ZiZC3uUipDulInNwoAy+W69ZUVSQUrpcY1tIckrkrOWQaqdKR+HzRl4mxbpXZDUWcd2a72xHKe28/wjd+FH63HIkLb2N1M2vlGmdh1fch8paPjPo8BunB1QTJ+zxoS8xB5jWPZqmQ=
    on:
      branch: master
      tags: false
      condition: $TRAVIS_PYTHON_VERSION = "2.7"
  - provider: pypi
    distributions: sdist
    server: https://upload.pypi.org/legacy/
    user: iamjohnnym
    password:
      secure: K2swV6OVouJWL8grGGSmrZ/iq6cWuE3cIcXSTnKMSqSyD41EF8SNk+fTSY1dv17d0fxClWZ5ub5u9XHeJy9wuKsl9gyaPPFvlnF2HVVoKdnfr+J6mot8AIh3zpdA+21AzlX3NssT5Y+5RLypOPLzyDHJm7fEidqRSnIDacnN6vRo6o/PbFgGDTw3sK6E7z8Ppg9BjGtsBOsK3NH5pfFkDVdEzO+GzPRoegDTpackDvg7w8d/7bAbKcdQhDVzNeU2fSS/eBd1vwG5LVpB9pEqOAIfGihIPgI81RMj4gJtKiEAO/9zbvna6xgGo6rf+U8N2ApeTDQfvplG2VMS4xdINdtyEEDyxYBkey+r2dM7+uHnZmOt61UXf4pZQVOj0aGjF7SaQgTKfDu8tgsw02fsA2RfqFLvF+X5CYL33nPGLaWbQHUgSP0vpe26NWGwA4G/39XQP56QckkTx9RwqZ+f/FreBGNNnvQ/qQ0yPaZYMmo6JJ6RUibUVXHqeN2NfCrjHA275SR6e1Dz8ZbZD5KNwzR6D/FJpgMl40ZiZC3uUipDulInNwoAy+W69ZUVSQUrpcY1tIckrkrOWQaqdKR+HzRl4mxbpXZDUWcd2a72xHKe28/wjd+FH63HIkLb2N1M2vlGmdh1fch8paPjPo8BunB1QTJ+zxoS8xB5jWPZqmQ=
    on:
      branch: master
      tags: true
      condition: $TRAVIS_PYTHON_VERSION = "2.7"
